### PR TITLE
Change email driver to smtp and get invitations working

### PR DESCRIPTION
**Pull request by nicmana**
Pretty small commit. I added a view that pops up after an email is sent. Also I moved the logic into a EmailController from that route as per my conversation with @GregJoubert. Look in the home.blade.php to see the email logic being called for emails (it's in a comment, I figured I'd leave it there for now, just so people can see it).

### CODE REVIEW

**Comment by nicmana** [comment]
@GregJoubert @delroyhiebert @JenCabral @maxewaschuk @bmansell, any thoughts?

**Comment by nicmana** [comment]
Haha, PHPStorm did that. It's just the IDE's spellchecker. I don't think it will cause a problem. All it does is adds Laravel specific words that I added to the dictionary. Worst case scenario, it won't read the dictionary when you guys run it, best case it won't say as much stuff is spelled wrong. 

That's a good point though, when I have a second I will go through and add all the IDE config files to the .gitignore file, since I'm pretty sure we can do without them in the repo. 

@delroyhiebert

**Comment by nicmana** [comment]
On the other hand, it might be nice to share IDE settings. I think it is something that can be discussed later, but isn't really important right now.

**Comment by delroyhiebert** [comment]
We might all be using different IDEs so we should not be sharing settings. Other than that this pull request should be good to go.

**Pull request merged**
