### PR TITLE
Implemented API consumption for web app

### PR DESCRIPTION
**Pull request by delroyhiebert**
Web app now uses ( or parts use ) the Restful API.
This process also lead to removal of business logic from our controllers.

### CODE REVIEW

**Comment by bmansell** [comment]
Looks good after a quick run through. Someone want to take a closer look?

**Comment by minnerthecat** [comment]
Viewing event details doesn't work. I am going to review the other features and attempt to fix them. I managed to fix the public/local city filter again.

**Comment by maxewaschuk** [comment]
There is a var_dump somewhere on successful event creation, attempting to track it down.

**Comment by delroyhiebert** [comment]
Merged in new bug fixes from @maxewaschuk

**Pull request merged**
