### PR TITLE
Iteration3 merging into master

### PR DESCRIPTION
**Pull request by delroyhiebert**
Development from iteration 3 on the iteration3 branch needs to be merged into master for the iteration deadline.
This includes android app development, new web app features, bug fixes, and additional test cases

### CODE REVIEW

**Comment by delroyhiebert** [comment]
Further development from this iteration before the deadline will be pushed directly to master

**Comment by minnerthecat** [comment]
approved

**Comment by JenCabral** [comment]
Looks great to me

**Comment by nicmana** [comment]
so good!

**Pull request merged**
