### PR TITLE
refactored event controller & added tabs

### PR DESCRIPTION
**Pull request by delroyhiebert**
-Refactored event controller - removed db access
-Added tabs for event creation (still needs error handling to be adjusted)
-Added event item list (doesn't save anything yet)
@bmansell @JenCabral @GregJoubert @maxewaschuk @nickmanaigre 

I would like to instead of having a giant create event file, have the file call other files for the tab contents but I don't know how to do that and I haven't really looked into it but I'm sure its possible. For that reason I haven't removed the old files, we just don't end up calling them with this setup at the moment.

### CODE REVIEW

**Comment by minnerthecat** [comment]
This looks good to me, we should just makes sure we address those TODO's as soon as we can

**Comment by minnerthecat** [comment]
There are also some conflicts with the last branch that was merged!

**Comment by delroyhiebert** [comment]
Yeah I figured that would happen, I'll resolve them tonight!

**Comment by GregJoubert** [comment]
Once the conflicts are handled it looks good to me. Not sure if we want to issue track TODOs in issues

**Comment by delroyhiebert** [comment]
Conflicts handled

**Pull request merged**
