### PR TITLE
Tickets

### PR DESCRIPTION
**Pull request by minnerthecat**
Added ticket sales to the app!

### CODE REVIEW

**Comment by delroyhiebert** [comment]
Looks good to me! AppVeyor agrees!

**Comment by minnerthecat** [comment]
does AppVeyor count as a second approval?

**Comment by delroyhiebert** [comment]
lol i don't think so, we should get another set of eyes on it

**Comment by GregJoubert** [comment]
do we need to be making tests for the code we create? Other than that it looks good.

**Pull request merged**
